import {
  ALL_CITIES_NAMES,
  DEFAULT_CITY,
  DEFAULT_SEARCH_PARAMS,
  DEFAULT_STYLES_CONTAINER,
  DEFAULT_STYLES_IMAGE,
  PAGE_TITLE
} from './defaults';

export {
  ALL_CITIES_NAMES,
  DEFAULT_CITY,
  DEFAULT_SEARCH_PARAMS,
  DEFAULT_STYLES_CONTAINER,
  DEFAULT_STYLES_IMAGE,
  PAGE_TITLE
};
